apiVersion: serving.knative.dev/v1alpha1
kind: Service
metadata:
  name: knative-serverless
  namespace: default
spec:
  template:
    spec:
      containers:
        - image: sankarge/knative-1:v1
          imagePullPolicy: Never
          env:
            - name: TARGET
              value: "Spring Boot Application"